### ISSUE TITLE
#<NoMethodError: undefined method `each_key' for #<ActionController::Parameters:0x0000561e5afc6830> Did you mean?  each_pair>

### ISSUE THREAD

**Issue by huacnlee** [ruby-china/homeland#1009]
```js

/var/www/homeland/app/controllers/settings_controller.rb:92:in `update_reward'
/var/www/homeland/app/controllers/settings_controller.rb:30:in `update'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/abstract_controller/base.rb:194:in `process_action'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/action_controller/metal/rendering.rb:30:in `process_action'
/var/www/homeland/vendor/bundle/ruby/2.5.0/gems/actionpack-5.2.0.rc1/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
```

**Comment by lihuazhang** [comment]
however in Rails 5 ActionController::Parameters now returns an Object instead of a Hash
