### ISSUE TITLE
undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by astaxie** [ruby-china/homeland#1152]
```
Method:      PUT
URL:         /setting
Parameters:
             {
               "_method": "put",
               "authenticity_token": "[FILTERED]",
               "by": "reward"
             }
Controller:  settings#update
RequestId:   13f9790d-f7ab-418b-9e16-1acd45c3a51a
User-Agent:  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.100 Safari/537.36
Remote IP:   172.21.0.8
Language:    zh,en;q=0.9,en-US;q=0.8,zh-CN;q=0.7
Server:      98beb927d25f
Process:     19

--------------------------------------------------

#<NoMethodError: undefined method `[]' for nil:NilClass>


/home/app/homeland/app/controllers/settings_controller.rb:94:in `update_reward'
/home/app/homeland/app/controllers/settings_controller.rb:30:in `update'
```

**Comment by IoTFinal** [comment]
插件安装了吗？要在后台安装插件

**Comment by astaxie** [comment]
安装了的

**Comment by zhengpd** [comment]
@astaxie 什么操作触发的？可以稳定重现吗？

**Comment by oslivan** [comment]
多看接口文档，没传 user 参数，使用问题！
