### ISSUE TITLE
源码方式编译镜像，启动报错

### ISSUE THREAD

**Issue by polandeme** [ruby-china/homeland#1164]
采用源码方式编译出来了镜像，然后使用 homeland-docker 下的方式指定镜像启动。但是ES 报错
```
Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [title : {term_vector=yes, type=text}] [body : {term_vector=yes, type=text}]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [properties]: Root mapping definition has unsupported parameters:  [title : {term_vector=yes, type=text}] [body : {term_vector=yes, type=text}]","caused_by":{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [title : {term_vector=yes, type=text}] [body : {term_vector=yes, type=text}]"}},"status":400}
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/elasticsearch-transport-7.6.0/lib/elasticsearch/transport/transport/base.rb:205:in `__raise_transport_error'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/elasticsearch-transport-7.6.0/lib/elasticsearch/transport/transport/base.rb:333:in `perform_request'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/elasticsearch-transport-7.6.0/lib/elasticsearch/transport/transport/http/faraday.rb:24:in `perform_request'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/elasticsearch-transport-7.6.0/lib/elasticsearch/transport/client.rb:163:in `perform_request'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/elasticsearch-api-7.6.0/lib/elasticsearch/api/namespace/common.rb:25:in `perform_request'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/elasticsearch-api-7.6.0/lib/elasticsearch/api/actions/indices/create.rb:33:in `create'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/elasticsearch-model-7.1.0/lib/elasticsearch/model/indexing.rb:252:in `create_index!'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/elasticsearch-model-7.1.0/lib/elasticsearch/model/importing.rb:155:in `import'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/elasticsearch-rails-7.1.0/lib/elasticsearch/rails/tasks/import.rb:80:in `block (3 levels) in <main>'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/usr/local/bundle/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/usr/local/bundle/bin/bundle:23:in `load'
/usr/local/bundle/bin/bundle:23:in `<main>'
Tasks: TOP => elasticsearch:import:model
```

看报错应该是 ES 版本太高问题，但是不确定为什么会产生这个问题

另外，怎么才可以修改源码，编译镜像启动呀，还是说 docker 模式只能使用 homeland-docker 项目部署

**Comment by polandeme** [comment]
将 homeland-docker 的 es 版本改为和源码一样冲洗构建就可以了
