### ISSUE TITLE
请问如何查看日志，系统经常报错但是看不到具体的错误原因

### ISSUE THREAD

**Issue by zwdgit** [ruby-china/homeland#1202]

**Comment by zwdgit** [comment]
![image](https://user-images.githubusercontent.com/28926324/96524182-1cb07a00-12aa-11eb-91e8-82d8ed171c3f.png)
这是配置的邮件服务，用的忘记密码做的测试，点击找回密码之后就跳转到这个页面了，也不知道到底哪里出的错

```
mailer_provider=smtp
mailer_sender=no-reply@sdyx.tech
mailer_options.address=smtp.qiye.aliyun.com
mailer_options.port=465
mailer_options.user_name=no-reply@sdyx.tech
mailer_options.password=z123456
mailer_options.authentication=login
mailer_options.enable_starttls_auto=true
mailer_options.openssl_verify_mode=true
mailer_options.ssl=true
```

**Comment by zwdgit** [comment]
使用 docker logs homeland_app 查看的日志是这样的：
```
[2020-10-20T00:16:24.910569 #35]  INFO -- : [442568fb-361c-4966-9b7e-70156f3b98ea] method=POST path=/account/password format=html controller=Users::PasswordsController action=create status=500 error='Errno::ECONNREFUSED: Connection refused - connect(2) for "" port ' duration=790.42 view=0.00 db=7.48
F, [2020-10-20T00:16:24.923531 #35] FATAL -- : [442568fb-361c-4966-9b7e-70156f3b98ea]
[442568fb-361c-4966-9b7e-70156f3b98ea] Errno::ECONNREFUSED (Connection refused - connect(2) for "" port ):
[442568fb-361c-4966-9b7e-70156f3b98ea]
[442568fb-361c-4966-9b7e-70156f3b98ea] app/controllers/users/passwords_controller.rb:14:in `create'
[442568fb-361c-4966-9b7e-70156f3b98ea] app/controllers/application_controller/localize.rb:26:in `set_time_zone'
```
