### ISSUE TITLE
找回密码异常

### ISSUE THREAD

**Issue by zwdgit** [ruby-china/homeland#1205]
注册后能正常发送并接收到邮件，但是忘记密码会报异常

异常日志：
```
Method:      POST
URL:         /account/password
Parameters:
             {
               "authenticity_token": "[FILTERED]",
               "user": {
                 "email": "zhu_wd@163.com"
               },
               "_rucaptcha": "jaabb",
               "commit": "找回密码"
             }
Controller:  users/passwords#create
RequestId:   1c0eb0ca-149e-4fb3-9e14-16a81eee6ce1
User-Agent:  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.80 Safari/537.36
Remote IP:   172.20.0.7
Language:    zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7
Server:      c06c6d2ccf17
Process:     11

--------------------------------------------------

#<Errno::ECONNREFUSED: Connection refused - connect(2) for "" port >


/usr/local/lib/ruby/2.7.0/net/smtp.rb:539:in `initialize'
/usr/local/lib/ruby/2.7.0/net/smtp.rb:539:in `open'
/usr/local/lib/ruby/2.7.0/net/smtp.rb:539:in `tcp_socket'
/usr/local/lib/ruby/2.7.0/net/smtp.rb:549:in `block in do_start'
/usr/local/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
/usr/local/lib/ruby/2.7.0/timeout.rb:105:in `timeout'
/usr/local/lib/ruby/2.7.0/net/smtp.rb:548:in `do_start'
/usr/local/lib/ruby/2.7.0/net/smtp.rb:518:in `start'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!'
```

**Comment by itviewer** [comment]
@zwdgit 
见 https://github.com/ruby-china/homeland/issues/1221

> 需要说明的是，类似 mailer_options.ssl 配置方式 ENV 根本获取不到内容，必须使用 mailer_options_ssl 方式，其它mailer_options一样

不要用 . 的格式

**Comment by huacnlee** [comment]
我刚才试了一下，通过 `.env` 配置一个测试，能读取到的

2.7.0 :001 > ENV["mailer.ssl"]
 => "123"
