### ISSUE TITLE
3.7 版本进入 console 出现 cannot load such file -- irb/easter-egg

### ISSUE THREAD

**Issue by lework** [ruby-china/homeland#1217]
版本
`homeland/homeland:3-7-latest`

```bash
# make console
Starting homeland_postgresql ... 
Starting homeland_redis ... done
Traceback (most recent call last):
        38: from bin/rails:4:in `<main>'
        37: from /home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:324:in `require'
        36: from /home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:291:in `load_dependency'
        35: from /home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:324:in `block in require'
        34: from /home/app/homeland/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        33: from /home/app/homeland/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        32: from /home/app/homeland/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        31: from /home/app/homeland/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        30: from /home/app/homeland/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        29: from /home/app/homeland/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.3/lib/rails/commands.rb:18:in `<main>'
        28: from /home/app/homeland/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.3/lib/rails/command.rb:44:in `invoke'
        27: from /home/app/homeland/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.3/lib/rails/command.rb:70:in `find_by_namespace'
        26: from /home/app/homeland/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.3/lib/rails/command/behavior.rb:39:in `lookup'
        25: from /home/app/homeland/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.3/lib/rails/command/behavior.rb:39:in `each'
        24: from /home/app/homeland/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.3/lib/rails/command/behavior.rb:40:in `block in lookup'
        23: from /home/app/homeland/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.3/lib/rails/command/behavior.rb:40:in `each'
        22: from /home/app/homeland/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.3/lib/rails/command/behavior.rb:44:in `block (2 levels) in lookup'
        21: from /home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:324:in `require'
        20: from /home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:291:in `load_dependency'
        19: from /home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:324:in `block in require'
        18: from /home/app/homeland/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        17: from /home/app/homeland/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        16: from /home/app/homeland/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        15: from /home/app/homeland/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        14: from /home/app/homeland/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        13: from /home/app/homeland/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.3/lib/rails/commands/console/console_command.rb:3:in `<main>'
        12: from /home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:324:in `require'
        11: from /home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:291:in `load_dependency'
        10: from /home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:324:in `block in require'
         9: from /home/app/homeland/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
         8: from /home/app/homeland/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
         7: from /home/app/homeland/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
         6: from /home/app/homeland/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
         5: from /home/app/homeland/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
         4: from /usr/local/lib/ruby/2.7.0/irb.rb:24:in `<main>'
         3: from /home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:324:in `require'
         2: from /home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:291:in `load_dependency'
         1: from /home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/dependencies.rb:324:in `block in require'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/bootsnap-1.4.8/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:34:in `require': cannot load such file -- irb/easter-egg (LoadError)
make: *** [console] Error 1
```

**Comment by huacnlee** [comment]
已修复

https://github.com/ruby-china/homeland/commit/33501800654048d95c103e9987595033f0b90e3f

原因是 Ruby 2.7.1 里面的 Bug
