### ISSUE TITLE
对帖子加精出现: 验证失败: 回复内容请勿回复无意义的内容，如你想收藏或赞这篇帖子，请用帖子后面的功能。

### ISSUE THREAD

**Issue by lework** [ruby-china/homeland#1218]
版本: `3.7.1`

```bash
Method:      POST
URL:         /topics/159/action?type=excellent
Parameters:
             {
               "type": "excellent",
               "id": "159"
             }
Controller:  topics#action
RequestId:   26c76c2a-55d5-460a-9122-611fb41563f6
User-Agent:  Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36
Remote IP:   172.27.0.7
Language:    zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7
Server:      ec080167e2ef
Process:     16

--------------------------------------------------

#<ActiveRecord::RecordInvalid: 验证失败: 回复内容请勿回复无意义的内容，如你想收藏或赞这篇帖子，请用帖子后面的功能。>


/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/validations.rb:80:in `raise_validation_error'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/validations.rb:53:in `save!'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/transactions.rb:318:in `block in save!'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/transactions.rb:375:in `block in with_transaction_returning_status'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/abstract/database_statements.rb:278:in `transaction'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/transactions.rb:212:in `transaction'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/transactions.rb:366:in `with_transaction_returning_status'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/transactions.rb:318:in `save!'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/suppressor.rb:48:in `save!'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/persistence.rb:55:in `create!'
/home/app/homeland/app/models/reply.rb:72:in `create_system_event!'
/home/app/homeland/app/models/topic/actions.rb:23:in `block in excellent!'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `block in transaction'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/abstract/transaction.rb:280:in `block in within_new_transaction'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/abstract/transaction.rb:278:in `within_new_transaction'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/connection_adapters/abstract/database_statements.rb:280:in `transaction'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/transactions.rb:212:in `transaction'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/transactions.rb:306:in `transaction'
/home/app/homeland/app/models/topic/actions.rb:22:in `excellent!'
/home/app/homeland/app/controllers/topics_controller.rb:138:in `action'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/abstract_controller/base.rb:195:in `process_action'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_controller/metal/rendering.rb:30:in `process_action'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
/home/app/homeland/app/controllers/application_controller.rb:164:in `set_time_zone'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:139:in `run_callbacks'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/abstract_controller/callbacks.rb:41:in `process_action'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_controller/metal/rescue.rb:22:in `process_action'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/notifications.rb:180:in `block in instrument'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/notifications.rb:180:in `instrument'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.3.3/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/abstract_controller/base.rb:136:in `process'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/actionview-6.0.3.3/lib/action_view/rendering.rb:39:in `process'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_controller/metal.rb:190:in `dispatch'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_controller/metal.rb:254:in `dispatch'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_dispatch/routing/route_set.rb:33:in `serve'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_dispatch/journey/router.rb:49:in `block in serve'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_dispatch/journey/router.rb:32:in `each'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_dispatch/journey/router.rb:32:in `serve'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_dispatch/routing/route_set.rb:834:in `call'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:192:in `call!'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/omniauth-1.9.1/lib/omniauth/strategy.rb:169:in `call'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/http_accept_language-2.1.1/lib/http_accept_language/middleware.rb:14:in `call'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/rack-attack-6.3.1/lib/rack/attack.rb:97:in `call'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/rack-attack-6.3.1/lib/rack/attack.rb:111:in `call'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/exception_notification-4.4.3/lib/exception_notification/rack.rb:49:in `call'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:40:in `call'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/cookies.rb:648:in `call'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/callbacks.rb:101:in `run_callbacks'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/lograge-0.11.2/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.3/lib/rails/rack/logger.rb:26:in `block in call'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/tagged_logging.rb:80:in `block in tagged'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/tagged_logging.rb:28:in `tagged'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/tagged_logging.rb:80:in `tagged'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.3/lib/rails/rack/logger.rb:26:in `call'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.3.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.3.3/lib/action_dispatch/middleware/host_authorization.rb:76:in `call'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/railties-6.0.3.3/lib/rails/engine.rb:527:in `call'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/puma-5.0.0/lib/puma/configuration.rb:238:in `call'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/puma-5.0.0/lib/puma/server.rb:620:in `handle_request'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/puma-5.0.0/lib/puma/server.rb:377:in `process_client'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/puma-5.0.0/lib/puma/server.rb:231:in `block in run'
/home/app/homeland/vendor/bundle/ruby/2.7.0/gems/puma-5.0.0/lib/puma/thread_pool.rb:141:in `block in spawn_thread'
```

**Comment by Dounx** [comment]
可以看看管理后台 -> 全局设置 -> ban_words_on_reply 中是不是有空行，删掉应该就好了。

如果 ban_words_on_reply 无任何内容直接更新一般估计也会好。

**Comment by lework** [comment]
谢谢，就是这个问题导致的。
