### ISSUE TITLE
undefined method `strip' for ["alipay", ""]:Array

### ISSUE THREAD

**Issue by astaxie** [ruby-china/homeland#1262]
Method:      GET
URL:         /admin/users/10440/edit
Controller:  admin/users#edit
RequestId:   fc0a971d-2b24-42d2-8bbb-6e33995e40f1
User-Agent:  Mozilla/5.0 (Macintosh; Intel Mac OS X 11_1_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36
Remote IP:   172.24.0.7
Language:    zh-CN,zh;q=0.9,en;q=0.8,de;q=0.7,vi;q=0.6,zh-TW;q=0.5,da;q=0.4
Server:      33f38ad83cc7
Process:     15

--------------------------------------------------

#<ActionView::Template::Error: undefined method `strip' for ["alipay", ""]:Array>

/home/app/homeland/app/models/setting.rb:217:in `block in has_profile_field?'
/home/app/homeland/app/models/setting.rb:217:in `each'
/home/app/homeland/app/models/setting.rb:217:in `map'
/home/app/homeland/app/models/setting.rb:217:in `has_profile_field?'
/home/app/homeland/app/views/admin/users/_form.html.erb:18:in `block in

**Comment by astaxie** [comment]
已解决，老版本升级到新版本，数据库不会自动升级，删除老数据就可以了
