### ISSUE TITLE
点赞功能有问题

### ISSUE THREAD

**Issue by williamherry** [ruby-china/homeland#1363]
想用homeland搭建一个公司内部社区，发现有这个问题， 试了下Ruby China网站也有这个问题， 最新的Chrome和Safari都有问题，如下图，console里有js报错，点赞按钮页面会滚动到顶部

![ruby-china-bug](https://user-images.githubusercontent.com/1032483/201923929-60c0fc0c-28ee-4c6b-aac4-afcd3299a555.gif)

js报错信息

```
topics.js:311 Uncaught TypeError: this.subscribe is not a function
    at f.connected (topics.js:311:25)
    at actioncable.esm.js:418:111
    at Array.map (<anonymous>)
    at m.notify (actioncable.esm.js:418:26)
    at h.message (actioncable.esm.js:258:33)
app.js:185 NotificationsChannel.subscibe
topics.js:331 Uncaught TypeError: window.repliesChannel.subscribe is not a function
    at R.i.initCableUpdate (topics.js:331:36)
    at R.i.initialize (topics.js:30:10)
    at t.View (backbone.js:1:12415)
    at new R.i (backbone.js:1:19544)
    at R.i.initialize (app.js:33:27)
    at t.View (backbone.js:1:12415)
    at new R.i (backbone.js:1:19544)
    at HTMLDocument.<anonymous> (app.js:396:21)
    at o.dispatch (turbolinks.js:5:1411)
    at t.notifyApplicationAfterPageLoad (turbolinks.js:6:2784)
```

**Comment by huacnlee** [comment]
已经修好了

**Comment by williamherry** [comment]
效率真高 👍
