### ISSUE TITLE
搜索本站内容，和相关主题报错

### ISSUE THREAD

**Issue by ningzhang422** [ruby-china/homeland#921]
我想views 中的报错其根源在于elasticsearch 索引时也报错
当我尝试以下命令行时，
```bash
rails elasticsearch:import:model CLASS=Page FORCE=y
rails elasticsearch:import:model CLASS=Topic FORCE=y
rails elasticsearch:import:model CLASS=User FORCE=y
```
结果：
```bash
vagrant@precise64:~/vagrant$ rails elasticsearch:import:model CLASS=Topic FORCE=y --trace
** Invoke elasticsearch:import:model (first_time)
** Execute elasticsearch:import:model
rails aborted!
NameError: uninitialized constant Topic
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/elasticsearch-rails-0.1.9/lib/elasticsearch/rails/tasks/import.rb:49:in `eval'
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/elasticsearch-rails-0.1.9/lib/elasticsearch/rails/tasks/import.rb:49:in `eval'
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/elasticsearch-rails-0.1.9/lib/elasticsearch/rails/tasks/import.rb:49:in `block (3 levels) in <top (required)>'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:250:in `block in execute'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:250:in `each'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:250:in `execute'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:194:in `block in invoke_with_call_chain'
/home/vagrant/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:187:in `invoke_with_call_chain'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task.rb:180:in `invoke'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/application.rb:152:in `invoke_task'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/application.rb:108:in `block (2 levels) in top_level'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/application.rb:108:in `each'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/application.rb:108:in `block in top_level'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/application.rb:117:in `run_with_threads'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/application.rb:102:in `top_level'
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:14:in `block in run_rake_task'
/home/vagrant/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/application.rb:178:in `standard_exception_handling'
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands/rake_proxy.rb:11:in `run_rake_task'
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:51:in `run_command!'
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
/home/vagrant/vagrant/bin/rails:9:in `require'
/home/vagrant/vagrant/bin/rails:9:in `<top (required)>'
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `load'
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/spring-2.0.1/lib/spring/client/rails.rb:28:in `call'
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/spring-2.0.1/lib/spring/client/command.rb:7:in `call'
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/spring-2.0.1/lib/spring/client.rb:30:in `run'
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/spring-2.0.1/bin/spring:49:in `<top (required)>'
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `load'
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/spring-2.0.1/lib/spring/binstub.rb:31:in `<top (required)>'
/home/vagrant/vagrant/bin/spring:13:in `require'
/home/vagrant/vagrant/bin/spring:13:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => elasticsearch:import:model
```
版本：
```bash
vagrant@precise64:~/vagrant$ rails -v
Rails 5.0.2
vagrant@precise64:~/vagrant$ ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]

homeland master 版本
```
views 报错是起因：
```error
Elasticsearch::Transport::Transport::Errors::NotFound in Topics#show 

Showing /home/vagrant/vagrant/app/views/topics/_related_topics.html.erb where line #2 raised:

[404] {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","index":"topics","resource.type":"index_or_alias","resource.id":"topics"}],"type":"index_not_found_exception","reason":"no such index","index":"topics","resource.type":"index_or_alias","resource.id":"topics"},"status":404}

```
导致related_topics 方法中的 elasticsearch 报错：
```ruby
      size: size
    }
    self.class.__elasticsearch__.search(opts).records.to_a 
  end


```

**Comment by NeverMin** [comment]
@ningzhang422 参考 #892 这个来改

**Comment by ningzhang422** [comment]
@NeverMin 谢谢你的回复。
按照你的回复，我修改了topic.rb 中的 mapping 块。但是依然报错：
<img width="1168" alt="capture d ecran 2017-04-29 a 08 16 13" src="https://cloud.githubusercontent.com/assets/1186049/25553476/283b46f0-2cb4-11e7-84fc-957366abfdcb.png">

这是elasticsearch 版本：
```bash
vagrant@precise64:~/vagrant$ curl -XGET 'localhost:9200'
{
  "name" : "Nicholas Maunder",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "2.3.5",
    "build_hash" : "90f439ff60a3c0f497f91663701e64ccd01edbb4",
    "build_timestamp" : "2016-07-27T10:36:52Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.0"
  },
  "tagline" : "You Know, for Search"
}
```

这是我试着手动添加索引时的结果：

```bash
vagrant@precise64:~/vagrant$ bin/rake elasticsearch:import:model CLASS=Topic FORCE=true
Running via Spring preloader in process 27273
[!!!] Index does not exist (Elasticsearch::Transport::Transport::Errors::NotFound)
rake aborted!
Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"No handler for type [text] declared on field [body]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [topic]: No handler for type [text] declared on field [body]","caused_by":{"type":"mapper_parsing_exception","reason":"No handler for type [text] declared on field [body]"}},"status":400}
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/elasticsearch-transport-5.0.3/lib/elasticsearch/transport/transport/base.rb:201:in `__raise_transport_error'
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/elasticsearch-transport-5.0.3/lib/elasticsearch/transport/transport/base.rb:318:in `perform_request'
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/elasticsearch-transport-5.0.3/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/elasticsearch-transport-5.0.3/lib/elasticsearch/transport/client.rb:131:in `perform_request'
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/elasticsearch-api-5.0.3/lib/elasticsearch/api/namespace/common.rb:21:in `perform_request'
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/elasticsearch-api-5.0.3/lib/elasticsearch/api/actions/indices/create.rb:86:in `create'
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/elasticsearch-model-0.1.9/lib/elasticsearch/model/indexing.rb:228:in `create_index!'
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/elasticsearch-model-0.1.9/lib/elasticsearch/model/importing.rb:116:in `import'
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/elasticsearch-rails-0.1.9/lib/elasticsearch/rails/tasks/import.rb:63:in `block (3 levels) in <top (required)>'
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `load'
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `block in load'
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
/home/vagrant/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `load'
-e:1:in `<main>'
Tasks: TOP => elasticsearch:import:model
(See full trace by running task with --trace)
```
麻烦给找找原因，谢谢。

**Comment by NeverMin** [comment]
@ningzhang422 2.x.x 版本不需要修改才对哦, 请问仅仅是执行 `rails elasticsearch:import:model CLASS=Topic FORCE=y` 才报错吗?

**Comment by ningzhang422** [comment]
@NeverMin 以下是homeland报错后，development.log ：
```bash
ActionView::Template::Error ([404] {"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","index":"topics","resource.type":"index_or_alias","resource.id":"topics"}],"type":"index_not_found_exception","reason":"no such index","index":"topics","resource.type":"index_or_alias","resource.id":"topics"},"status":404}):
    1: <% cache([@topic, 'related_topic', Date.current]) do %>
    2:   <% if @topic.related_topics.present? %>
    3:     <div class="panel panel-default">
    4:       <div class="panel-heading">相关话题</div>
    5:       <ul class="list-group">
  
app/models/topic.rb:93:in `related_topics'
app/views/topics/_related_topics.html.erb:2:in `block in _app_views_topics__related_topics_html_erb__256485334208955014_70171612703060'
app/helpers/application_helper.rb:123:in `cache'
```
由此我想尝试一下手动载入索引，即执行命令行：`rails elasticsearch:import:model CLASS=Topic FORCE=y`. 结果也报错。错误信息见上面回复。

谢谢回复。

**Comment by huacnlee** [comment]
用 Docker 部署吧，精力不够，没那么多时间来看各种场景的兼容

**Comment by ningzhang422** [comment]
@huacnlee 感谢回复，我试试用docker运行开发环境吧。
