### ISSUE TITLE
github 账号登录失败

### ISSUE THREAD

**Issue by lihuazhang** [ruby-china/homeland#938]
```log

#<NameError: undefined local variable or method `env' for #<Auth::OmniauthCallbacksController:0x007fbe8830b148>>


--------------------------------------------------
Method:     GET
URL:        http://testerhome.com/account/auth/github/callback?code=ace8f30ca89feb279c2c&state=bcfb360c8ad2ffa49f1a6623efae0eef7597207c708a9085
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
Language:   zh-CN,zh;q=0.8,ja;q=0.6,en;q=0.4
Server:     6c666be7d39e
Process:    8
--------------------------------------------------


(eval):7:in `github'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/abstract_controller/base.rb:186:in `process_action'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:131:in `run_callbacks'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_controller/metal/rescue.rb:20:in `process_action'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `block in instrument'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/notifications.rb:166:in `instrument'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.1/lib/active_record/railties/controller_runtime.rb:22:in `process_action'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/abstract_controller/base.rb:124:in `process'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.1/lib/action_view/rendering.rb:30:in `process'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_controller/metal.rb:189:in `dispatch'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_controller/metal.rb:253:in `dispatch'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_dispatch/routing/route_set.rb:31:in `serve'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_dispatch/routing/mapper.rb:16:in `block in <class:Constraints>'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_dispatch/routing/mapper.rb:46:in `serve'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_dispatch/journey/router.rb:46:in `block in serve'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_dispatch/journey/router.rb:33:in `each'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_dispatch/journey/router.rb:33:in `serve'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_dispatch/routing/route_set.rb:832:in `call'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:407:in `call_app!'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:361:in `callback_phase'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/omniauth-oauth2-1.4.0/lib/omniauth/strategies/oauth2.rb:75:in `callback_phase'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:230:in `callback_call'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:187:in `call!'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/omniauth-1.6.1/lib/omniauth/strategy.rb:167:in `call'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/http_accept_language-2.1.0/lib/http_accept_language/middleware.rb:14:in `call'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/rack-attack-5.0.1/lib/rack/attack.rb:147:in `call'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/exception_notification-4.2.1/lib/exception_notification/rack.rb:32:in `call'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/etag.rb:25:in `call'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/conditional_get.rb:25:in `call'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/head.rb:12:in `call'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:232:in `context'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/session/abstract/id.rb:226:in `call'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/cookies.rb:613:in `call'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/callbacks.rb:97:in `run_callbacks'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/callbacks.rb:24:in `call'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/railties-5.1.1/lib/rails/rack/logger.rb:36:in `call_app'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/railties-5.1.1/lib/rails/rack/logger.rb:24:in `block in call'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/tagged_logging.rb:69:in `block in tagged'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/tagged_logging.rb:26:in `tagged'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/tagged_logging.rb:69:in `tagged'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/railties-5.1.1/lib/rails/rack/logger.rb:24:in `call'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/request_id.rb:25:in `call'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/method_override.rb:22:in `call'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.1/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/executor.rb:12:in `call'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/static.rb:125:in `call'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/actionpack-5.1.1/lib/action_dispatch/middleware/ssl.rb:66:in `call'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/rack-cors-0.4.1/lib/rack/cors.rb:81:in `call'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/rack-utf8_sanitizer-1.3.2/lib/rack/utf8_sanitizer.rb:19:in `call'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/railties-5.1.1/lib/rails/engine.rb:522:in `call'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/puma-3.9.1/lib/puma/configuration.rb:224:in `call'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/puma-3.9.1/lib/puma/server.rb:602:in `handle_request'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/puma-3.9.1/lib/puma/server.rb:435:in `process_client'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/puma-3.9.1/lib/puma/server.rb:299:in `block in run'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/puma-3.9.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

**Comment by lihuazhang** [comment]
https://github.com/ruby-china/homeland/pull/939
