### ISSUE TITLE
请求首页跳到500页面

### ISSUE THREAD

**Issue by chenchiwei** [ruby-china/homeland#962]
请求首页跳转动500页面，看日志报以下错误，请问下是什么原因呢？

**Comment by chenchiwei** [comment]
`I, [2017-10-20T05:08:41.652772 #26964]  INFO -- : Started GET "/" for 127.0.0.1 at 2017-10-20 05:08:41 +0000
I, [2017-10-20T05:08:41.653821 #26964]  INFO -- : Processing by HomeController#index as HTML
I, [2017-10-20T05:08:41.656466 #26964]  INFO -- : Completed 500 Internal Server Error in 2ms (ActiveRecord: 0.5ms)
F, [2017-10-20T05:08:41.657791 #26964] FATAL -- :
F, [2017-10-20T05:08:41.658513 #26964] FATAL -- : NoMethodError (private method `warn' called for nil:NilClass):
F, [2017-10-20T05:08:41.658597 #26964] FATAL -- :
F, [2017-10-20T05:08:41.658678 #26964] FATAL -- : exception_notification (4.2.2) lib/exception_notifier.rb:116:in `rescue in fire_notification'
exception_notification (4.2.2) lib/exception_notifier.rb:111:in `fire_notification'
exception_notification (4.2.2) lib/exception_notifier.rb:55:in `block in notify_exception'
exception_notification (4.2.2) lib/exception_notifier.rb:54:in `each'
exception_notification (4.2.2) lib/exception_notifier.rb:54:in `notify_exception'
exception_notification (4.2.2) lib/exception_notification/rack.rb:51:in `rescue in call'
exception_notification (4.2.2) lib/exception_notification/rack.rb:41:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'`

**Comment by 1c7** [comment]
2018-5-24 用 puma 碰到类似的问题：
![image](https://user-images.githubusercontent.com/1804755/40477348-d4699ca4-5f78-11e8-9047-917cfeb37877.png)

```
I, [2018-05-24T17:26:45.809130 #54549]  INFO -- : Started GET "/" for 127.0.0.1 at 2018-05-24 17:26:45 +0800
I, [2018-05-24T17:26:45.810283 #54549]  INFO -- : Processing by HomeController#index as HTML
I, [2018-05-24T17:26:45.816998 #54549]  INFO -- : Completed 500 Internal Server Error in 7ms
F, [2018-05-24T17:26:45.821290 #54549] FATAL -- :   
F, [2018-05-24T17:26:45.822008 #54549] FATAL -- : NoMethodError (private method `warn' called for nil:NilClass):
F, [2018-05-24T17:26:45.822049 #54549] FATAL -- :   
F, [2018-05-24T17:26:45.822090 #54549] FATAL -- : exception_notification (4.2.2) lib/exception_notifier.rb:116:in `rescue in fire_notification'
exception_notification (4.2.2) lib/exception_notifier.rb:110:in `fire_notification'
exception_notification (4.2.2) lib/exception_notifier.rb:55:in `block in notify_exception'
exception_notification (4.2.2) lib/exception_notifier.rb:54:in `each'
exception_notification (4.2.2) lib/exception_notifier.rb:54:in `notify_exception'
exception_notification (4.2.2) lib/exception_notification/rack.rb:51:in `rescue in call'
exception_notification (4.2.2) lib/exception_notification/rack.rb:40:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.4) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.0.4) lib/rack/etag.rb:25:in `call'
rack (2.0.4) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.4) lib/rack/head.rb:12:in `call'
actionpack (5.2.0) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.0.4) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.4) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/cookies.rb:670:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.0) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.0) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.0) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.0) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.0) lib/rails/rack/logger.rb:26:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.4) lib/rack/method_override.rb:22:in `call'
rack (2.0.4) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
rack (2.0.4) lib/rack/sendfile.rb:111:in `call'
rack-cors (1.0.2) lib/rack/cors.rb:97:in `call'
rack-utf8_sanitizer (1.5.0) lib/rack/utf8_sanitizer.rb:22:in `call'
railties (5.2.0) lib/rails/engine.rb:524:in `call'
puma (3.11.4) lib/puma/configuration.rb:225:in `call'
puma (3.11.4) lib/puma/server.rb:632:in `handle_request'
puma (3.11.4) lib/puma/server.rb:446:in `process_client'
puma (3.11.4) lib/puma/server.rb:306:in `block in run'
puma (3.11.4) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
I, [2018-05-24T17:26:45.982450 #54549]  INFO -- : Started GET "/favicon.ico" for 127.0.0.1 at 2018-05-24 17:26:45 +0800
I, [2018-05-24T17:26:45.983592 #54549]  INFO -- : Processing by UsersController#show as HTML
I, [2018-05-24T17:26:45.983662 #54549]  INFO -- :   Parameters: {"id"=>"favicon.ico"}
I, [2018-05-24T17:26:45.990075 #54549]  INFO -- : Completed 500 Internal Server Error in 6ms
F, [2018-05-24T17:26:45.993811 #54549] FATAL -- :   
F, [2018-05-24T17:26:45.994496 #54549] FATAL -- : NoMethodError (private method `warn' called for nil:NilClass):
F, [2018-05-24T17:26:45.994536 #54549] FATAL -- :   
F, [2018-05-24T17:26:45.994598 #54549] FATAL -- : exception_notification (4.2.2) lib/exception_notifier.rb:116:in `rescue in fire_notification'
exception_notification (4.2.2) lib/exception_notifier.rb:110:in `fire_notification'
exception_notification (4.2.2) lib/exception_notifier.rb:55:in `block in notify_exception'
exception_notification (4.2.2) lib/exception_notifier.rb:54:in `each'
exception_notification (4.2.2) lib/exception_notifier.rb:54:in `notify_exception'
exception_notification (4.2.2) lib/exception_notification/rack.rb:51:in `rescue in call'
exception_notification (4.2.2) lib/exception_notification/rack.rb:40:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.4) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.0.4) lib/rack/etag.rb:25:in `call'
rack (2.0.4) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.4) lib/rack/head.rb:12:in `call'
actionpack (5.2.0) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.0.4) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.4) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/cookies.rb:670:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.0) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.0) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.0) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.0) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.0) lib/rails/rack/logger.rb:26:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.4) lib/rack/method_override.rb:22:in `call'
rack (2.0.4) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
rack (2.0.4) lib/rack/sendfile.rb:111:in `call'
rack-cors (1.0.2) lib/rack/cors.rb:97:in `call'
rack-utf8_sanitizer (1.5.0) lib/rack/utf8_sanitizer.rb:22:in `call'
railties (5.2.0) lib/rails/engine.rb:524:in `call'
puma (3.11.4) lib/puma/configuration.rb:225:in `call'
puma (3.11.4) lib/puma/server.rb:632:in `handle_request'
puma (3.11.4) lib/puma/server.rb:446:in `process_client'
puma (3.11.4) lib/puma/server.rb:306:in `block in run'
puma (3.11.4) lib/puma/thread_pool.rb:120:in `block in spawn_thread'

```

**Comment by 1c7** [comment]
```
RAILS_ENV="production" bundle exec rails s
```
本地跑 production 的时候遇到的

**Comment by 1c7** [comment]
## 问题解决
显然是忘记了初始化 production 的 db 和 assets precompile
为了在本地跑 production mode 的 homeland

1.
config/environments/
```
 config.public_file_server.enabled = true
```

2. 
```
RAILS_ENV=production rails db:create
RAILS_ENV=production rails db:migrate
RAILS_ENV=production rails assets:precompile
RAILS_ENV=production bundle exec rails s
```
