### ISSUE TITLE
在Teams中建了一个团队，然后想删除，发现无法删除

### ISSUE THREAD

**Issue by disney2002** [ruby-china/homeland#966]
删除时，报错，具体说应该是后台进入这个用户编辑时就报错。

错误信息如下：

`Association named 'authorizations' was not found on Team; perhaps you misspelled it?

#<ActionView::Template::Error: Association named 'authorizations' was not found on Team; perhaps you misspelled it?>

/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/associations.rb:263:in `association'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/activerecord-5.1.4/lib/active_record/associations/builder/association.rb:111:in `authorizations'
/var/www/homeland/app/views/admin/users/_form.html.erb:39:in `block in _app_views_admin_users__form_html_erb___1104851645704016277_69975217937720'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.4/lib/action_view/helpers/capture_helper.rb:39:in `block in capture'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.4/lib/action_view/helpers/capture_helper.rb:203:in `with_output_buffer'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.4/lib/action_view/helpers/capture_helper.rb:39:in `capture'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/actionview-5.1.4/lib/action_view/helpers/form_helper.rb:450:in `form_for'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/simple_form-3.5.0/lib/simple_form/action_view_extensions/form_helper.rb:26:in `block in simple_form_for'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/simple_form-3.5.0/lib/simple_form/action_view_extensions/form_helper.rb:45:in `with_simple_form_field_error_proc'
/var/www/homeland/vendor/bundle/ruby/2.4.0/gems/simple_form-3.5.0/lib/simple_form/action_view_extensions/form_helper.rb:25:in `simple_form_for'
/var/www/homeland/app/views/admin/users/_form.html.erb:1:in `_app_views_admin_users__form_html_erb___1104851645704016277_69975217937720'`

**Comment by disney2002** [comment]
删除一个用户没问题，可以删除。
