### ISSUE TITLE
数据库迁到mysql怎么做？

### ISSUE THREAD

**Issue by YUFENGWANG** [ruby-china/homeland#967]
求问大佬们，最近在基于homeland做二次开发，需要将数据库迁移到mysql，我更新了database.yml文件，然后rake db:setup的时候报错
```bash
Created database 'flkWeb-dev'
Created database 'flkWeb-test'
-- enable_extension("plpgsql")
   -> 0.0012s
-- create_table("actions", {:force=>:cascade})
   -> 0.0375s
-- create_table("authorizations", {:force=>:cascade})
rake aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: Specified key was too long; max key length is 3072 bytes: CREATE TABLE `authorizations` (`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, `provider` varchar(255) NOT NULL, `uid` varchar(1000) NOT NULL, `user_id` int NOT NULL, `created_at` datetime, `updated_at` datetime,  INDEX `index_authorizations_on_provider_and_uid`  (`provider`, `uid`)) ENGINE=InnoDB
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/mysql2-0.4.9/lib/mysql2/client.rb:120:in `_query'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/mysql2-0.4.9/lib/mysql2/client.rb:120:in `block in query'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/mysql2-0.4.9/lib/mysql2/client.rb:119:in `handle_interrupt'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/mysql2-0.4.9/lib/mysql2/client.rb:119:in `query'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:214:in `block (2 levels) in execute'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.4/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:213:in `block in execute'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block (2 levels) in log'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:611:in `block in log'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:603:in `log'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:212:in `execute'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/mysql/database_statements.rb:26:in `execute'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/schema_statements.rb:288:in `create_table'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:363:in `create_table'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:849:in `block in method_missing'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:818:in `block in say_with_time'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:818:in `say_with_time'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:838:in `method_missing'
/home/yufeng/flk/flkWeb/db/schema.rb:31:in `block in <top (required)>'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/schema.rb:48:in `instance_eval'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/schema.rb:48:in `define'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/schema.rb:44:in `define'
/home/yufeng/flk/flkWeb/db/schema.rb:13:in `<top (required)>'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `block in load'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:233:in `load_schema'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:255:in `block in load_schema_current'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:304:in `block in each_current_configuration'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:303:in `each'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:303:in `each_current_configuration'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:254:in `load_schema_current'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/railties/databases.rake:248:in `block (3 levels) in <top (required)>'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/railties/databases.rake:252:in `block (3 levels) in <top (required)>'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
/home/yufeng/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
/home/yufeng/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
Mysql2::Error: Specified key was too long; max key length is 3072 bytes
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/mysql2-0.4.9/lib/mysql2/client.rb:120:in `_query'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/mysql2-0.4.9/lib/mysql2/client.rb:120:in `block in query'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/mysql2-0.4.9/lib/mysql2/client.rb:119:in `handle_interrupt'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/mysql2-0.4.9/lib/mysql2/client.rb:119:in `query'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:214:in `block (2 levels) in execute'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:46:in `block in permit_concurrent_loads'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.4/lib/active_support/concurrency/share_lock.rb:185:in `yield_shares'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies/interlock.rb:45:in `permit_concurrent_loads'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:213:in `block in execute'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:612:in `block (2 levels) in log'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:611:in `block in log'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.4/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_adapter.rb:603:in `log'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:212:in `execute'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/mysql/database_statements.rb:26:in `execute'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract/schema_statements.rb:288:in `create_table'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:363:in `create_table'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:849:in `block in method_missing'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:818:in `block in say_with_time'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:818:in `say_with_time'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/migration.rb:838:in `method_missing'
/home/yufeng/flk/flkWeb/db/schema.rb:31:in `block in <top (required)>'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/schema.rb:48:in `instance_eval'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/schema.rb:48:in `define'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/schema.rb:44:in `define'
/home/yufeng/flk/flkWeb/db/schema.rb:13:in `<top (required)>'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `block in load'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:258:in `load_dependency'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.4/lib/active_support/dependencies.rb:286:in `load'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:233:in `load_schema'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:255:in `block in load_schema_current'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:304:in `block in each_current_configuration'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:303:in `each'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:303:in `each_current_configuration'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:254:in `load_schema_current'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/railties/databases.rake:248:in `block (3 levels) in <top (required)>'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/activerecord-5.1.4/lib/active_record/railties/databases.rake:252:in `block (3 levels) in <top (required)>'
/home/yufeng/.rvm/gems/ruby-2.4.0/gems/rake-12.1.0/exe/rake:27:in `<top (required)>'
/home/yufeng/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
/home/yufeng/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:schema:load
(See full trace by running task with --trace)

```

**Comment by huacnlee** [comment]
不支持

**Comment by YUFENGWANG** [comment]
好吧．看来只能根据error一个个去改了
